[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
senda_dapp = "HyavU5k2jA2D2oPUX7Ct8kUhXJQGaTum4nqnLW7f77wL"

[programs.devnet]
senda_dapp = "HyavU5k2jA2D2oPUX7Ct8kUhXJQGaTum4nqnLW7f77wL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./Turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
